#!/usr/bin/env python3
"""Generate Markdown navigation from explicit memberships; never infer research claims."""
from pathlib import Path
import argparse
import json
import re
from datetime import datetime
from zoneinfo import ZoneInfo
from health import parse_frontmatter

ROOT = Path(__file__).resolve().parents[1]
WIKI = ROOT / "wiki"
GENERATED = {
    "index.md": "Niuverse Wiki",
    "catalog.md": "完整目录",
    "papers.md": "论文库",
    "references.md": "Sources",
    "research-topics.md": "Topics",
    "syntheses/research-questions.md": "研究问题索引",
}
GROUPS = [("topic", "Topics"), ("concept", "Concepts"), ("source", "Sources"),
          ("synthesis", "Notes"),
          ("navigation", "其他目录")]


def document(name, body, description=""):
    existing = WIKI / name
    modified = parse_frontmatter(existing.read_text()).get("modified") if existing.exists() else None
    modified = modified or datetime.now(ZoneInfo("Asia/Shanghai")).date().isoformat()
    meta = {"title": GENERATED[name], "type": "navigation", "modified": modified,
            "tags": ["navigation", "learn"], "sources": [], "description": description}
    fm = "\n".join(f"{key}: {json.dumps(value, ensure_ascii=False)}" for key, value in meta.items())
    return f"---\n{fm}\n---\n\n<!-- Generated by tools/build_catalog.py; edit page metadata instead. -->\n\n{body.strip()}\n"


def link(path, meta):
    return f'[[{path.removesuffix(".md")}|{meta.get("nav_title") or meta.get("title", Path(path).stem)}]]'


def recent_updates(log_text, limit=5):
    """Use append order and recorded times; never infer operation times from file dates."""
    headers = list(re.finditer(r"^## \[(\d{4}-\d{2}-\d{2})\] (\w+) \| (.+)$", log_text, re.M))
    updates = []
    for i in range(len(headers) - 1, -1, -1):
        header = headers[i]
        body = log_text[header.end():headers[i + 1].start() if i + 1 < len(headers) else len(log_text)]
        recorded = re.search(r"^时间：(\d{4}-\d{2}-\d{2} \d{2}:\d{2})", body, re.M)
        targets = list(dict.fromkeys(re.findall(r"\[\[([^\]|]+)(?:\|[^\]]+)?\]\]", body)))
        updates.append((recorded.group(1) if recorded else header[1], header[3], targets))
        if len(updates) >= limit:
            break
    return updates


def outputs():
    pages = []
    for path in sorted(WIKI.rglob("*.md")):
        relative = path.relative_to(WIKI).as_posix()
        if relative in GENERATED or path.name in {"health-report.md", "lint-report.md"}:
            continue
        pages.append((relative, parse_frontmatter(path.read_text(encoding="utf-8"))))
    topics = [(p, f) for p, f in pages if f.get("type") == "topic"]
    entries = sorted(topics, key=lambda item: (int(item[1].get("nav_order", "999")), item[0]))
    main = [(p, f) for p, f in entries if f.get("entry") == "research"]
    tools = [(p, f) for p, f in entries if f.get("entry") == "tools"]
    questions = [(p, f) for p, f in topics if not f.get("entry")]
    nav = ["## 查找与回顾", "", "- [[references|Sources · 论文、文档与代码]]", "- [[papers|论文筛选]]",
           "- [[catalog|完整目录]]", "- [[overview|跨主题研究判断]]",
           "- [[syntheses/research-questions|研究问题索引]]", "- [[log|知识库日志]]"]
    home = ["机器人与具身智能研究笔记。按问题探索，沿证据深入。", "", "## Topics", ""]
    for p, f in main:
        home += ["- " + link(p, f) + "\n  " + f.get("description", "")]
    home += ["", "[[research-topics|全部 Topics]] · " + " · ".join(link(p, f) for p, f in tools), ""]
    updates = recent_updates((WIKI / "log.md").read_text(encoding="utf-8"))
    if updates:
        by_target = {p.removesuffix(".md"): (p, f) for p, f in pages}
        by_target.update({Path(p).stem: (p, f) for p, f in pages})
        home += ["## 最近更新", "", "时间为北京时间；旧记录未记时分的只显示日期。", ""]
        for timestamp, title, targets in updates:
            related = []
            for target in targets:
                page = by_target.get(target.split('#')[0])
                if page and page[1].get("type") == "redirect":
                    page = by_target.get(page[1].get("redirect_to", ""))
                if page:
                    related.append(link(*page))
                    if title.startswith("补充原始配图："):
                        title = "补充配图：" + (page[1].get("nav_title") or page[1]["title"])
            related = list(dict.fromkeys(related))
            home += [f"- **{timestamp}** · {title}" + ("\n  " + " · ".join(related[:2]) if related else "")]
        home += ["", "[[log|查看完整日志]]", ""]
    home += nav
    result = {"index.md": document("index.md", "\n".join(home))}
    topic_body = ["主题是相互交叉的阅读地图，论文和概念可以参与多个主题；专题笔记讨论具体研究问题。这里没有强制的父子归属。", "", "## 研究入口", ""]
    for p, f in main:
        topic_body.append("- " + link(p, f))
    topic_body += ["", "## 专题笔记", ""] + ["- " + link(p, f) for p, f in questions]
    topic_body += ["", "## 工具与工程笔记", ""] + ["- " + link(p, f) for p, f in tools]
    result["research-topics.md"] = document("research-topics.md", "\n".join(topic_body))
    question_body = ["问题、证据边界与补证优先级由各主题和专题维护；此处仅汇总可直接跳转的入口。", ""]
    for title, rows in [("研究地图", main), ("具体专题", questions), ("工具笔记", tools)]:
        question_body += ["## " + title, ""]
        question_body += [f'- [[{p[:-3]}#未解问题与优先补证|{f["title"]}]]' for p, f in rows] + [""]
    result["syntheses/research-questions.md"] = document("syntheses/research-questions.md", "\n".join(question_body))
    papers = [(p, f) for p, f in pages if f.get("source_type") == "paper"]
    papers.sort(key=lambda item: (-int(item[1].get("year", "0")) if item[1].get("year", "0").isdigit() else 0, item[0]))
    result["papers.md"] = document("papers.md", "按核实的文献年份排序；版本、译本及证据范围见各论文页。\n\n" + "\n".join(f'- {link(p, f)} · {f.get("year", "未核实")} · {f.get("venue", "发表信息见正文")}' for p, f in papers), "按主题、年份和关键词查找论文；共享基础通过正文链接阅读。")
    refs = [(p, f) for p, f in pages if f.get("type") == "source"]
    source_body = ["论文、代码和文档统一在这里查找，各页保留自己的版本和证据范围。按年份、主题筛选论文可用 [[papers|论文库]]。", ""]
    for kinds, title in [( {"paper"}, "Papers"), ({"repository"}, "Code"),
                         ({"documentation", "tutorial", "book"}, "Docs & Books"),
                         ({"project", "article"}, "Projects & Articles")]:
        rows = [(p, f) for p, f in refs if f.get("source_type") in kinds]
        if rows:
            source_body += ["## " + title, ""] + ["- " + link(p, f) for p, f in rows] + [""]
    result["references.md"] = document("references.md", "\n".join(source_body))
    catalog_pages = pages + [(p, {"title": title, "type": "navigation"}) for p, title in GENERATED.items() if p not in {"index.md", "catalog.md"}]
    directory = ["此页收录全部知识页；主题阅读入口见 [[research-topics|主题地图]]。", ""]
    for kind, title in GROUPS:
        rows = [(p, f) for p, f in catalog_pages if f.get("type") == kind]
        if rows:
            directory += ["## " + title, ""] + ["- " + link(p, f) for p, f in rows] + [""]
    redirects = [(p, f) for p, f in pages if f.get("type") == "redirect"]
    if redirects:
        directory += ["<details>", "<summary>旧地址</summary>", ""]
        directory += ["- " + link(p, f) for p, f in redirects] + ["", "</details>"]
    result["catalog.md"] = document("catalog.md", "\n".join(directory))
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for name, content in outputs().items():
        path = WIKI / name
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            stale.append(name)
            if not args.check:
                path.write_text(content, encoding="utf-8")
    print(("待更新：" if args.check else "已更新：") + ", ".join(stale) if stale else "目录已同步")
    return int(args.check and bool(stale))


if __name__ == "__main__":
    raise SystemExit(main())
